services:
  - type: web
    name: expense-tracker-api
    env: python
    plan: free
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OCR_SPACE_API_KEY
        sync: false
      - key: APP_TZ
        value: Australia/Sydney
      - key: APP_CURRENCY
        value: AUD
