name: Force Frontend Deploy

on:
  workflow_dispatch:
  push:
    paths: [ 'frontend/**', '.github/workflows/force-deploy.yml' ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "force-pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install and Build
        run: |
          cd frontend
          npm ci
          npm run build
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
